version: "3.9"

services:
  react:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: fullstack_auth_react
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
