version: "3.9"

volumes:
  postgres_data:
  smtp_data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: fullstack_auth_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/postgres.env
    expose:
      - "5432"
    ports:
      - "5433:5432"

  django:
    build:
      context: ./core
      dockerfile: ./docker/Dockerfile
    command: /django.sh
    container_name: fullstack_auth_django
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/django.env
      - ./.envs/postgres.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - smtp

  celery-beat:
    build:
      context: ./core
      dockerfile: ./docker/Dockerfile
    command: /celery/beat.sh
    container_name: fullstack_auth_celery_beat
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/django.env
      - ./.envs/postgres.env
    depends_on:
      - postgres
      - redis

  celery-worker:
    build:
      context: ./core
      dockerfile: ./docker/Dockerfile
    command: /celery/worker.sh
    container_name: fullstack_auth_celery_worker
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/django.env
      - ./.envs/postgres.env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    container_name: fullstack_auth_redis

  flower:
    build:
      context: ./core
      dockerfile: ./docker/Dockerfile
    command: /celery/flower.sh
    container_name: fullstack_auth_flower
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/django.env
      - ./.envs/postgres.env
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis

  react:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: fullstack_auth_react
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  smtp:
    image: rnwood/smtp4dev
    container_name: fullstack_auth_smtp
    ports:
      - "5000:80"
      - "2525:25"
    volumes:
      - smtp_data:/app/Smtp4dev/DB
