version: "3.9"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: fullstack_auth_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/postgres.env
    expose:
      - "5432"
    ports:
      - "5433:5432"

  django:
    build:
      context: ./core
      dockerfile: ./docker/Dockerfile
    command: /django.sh
    container_name: fullstack_auth_django_tests
    volumes:
      - ./core:/src:z
    env_file:
      - ./.envs/tests.env
      - ./.envs/postgres.env
      - ./.envs/email.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres





















