name: backend-example

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
    pull_request:
        branches:
            - main
            - develop
            - master

    push:
        branches:
            - main
            - develop
            - master
        ignore:
            - ".idea"
            - "frontend/**"
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: Build the Stack
              run: docker-compose build
            - name: Tear down the Stack
              run:  docker-compose down

    pytest:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: Run DB Migrations
              run: docker-compose run --rm django python manage.py migrate
            - name: Run Django Tests
              run: docker-compose run django pytest -s -v --no-migrations

    linters:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: Checkout Code Repository
              uses: actions/checkout@v3
            - name: ruff
              uses: chartboost/ruff-action@v1
